FROM tomcat:8-jre8
MAINTAINER madalinl@gmail.com

# Create it with
#       docker build -t madalinl/tomcat -f /path/to/this/Dockerfile .
# Create data only container
#		docker run --name tomcat-data -v /usr/local/tomcat/conf -v /usr/local/tomcat/lib -v /usr/local/tomcat/logs -v /usr/local/tomcat/webapps  busybox true
# Run it with
#       docker run -it --name tomcat -p 8080:8080 --volumes-from tomcat-data madalinl/tomcat
