FROM mysql:5.6
MAINTAINER madalinl@gmail.com

# Create it with
#       docker build -t madalinl/mysql -f /path/to/this/Dockerfile .
# Create data only container
#	docker run --name mysql-data -v /var/lib/mysql busybox true
# Run it with
#       docker run -it --name mysql -p 3306:3306 --volumes-from mysql-data madalinl/mysql

