FROM postgres:latest
MAINTAINER madalinl@gmail.com

# Create it with
#       docker build -t madalinl/postgres -f /path/to/this/Dockerfile .
# Create data only container
#		docker run --name postgres-data -v /var/lib/postgresql/data busybox true
# Run it with
#       docker run -it --name postgres -p 5432:5432 --volumes-from postgres-data madalinl/postgres
