FROM postgres:latest
MAINTAINER madalinl@gmail.com

# Create it with
#       docker build -t madalinl/postgres -f /path/to/this/Dockerfile .
# Run it with
#       docker run -it --name postgres -p 5432:5432 madalinl/postgres

